create table quiz_sets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text check (char_length(name) > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table quiz_sets enable row level security;
create policy "Individuals can create quiz_sets." on quiz_sets for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own quiz_sets. " on quiz_sets for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own quiz_sets." on quiz_sets for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own quiz_sets." on quiz_sets for
    delete using (auth.uid() = user_id);
