create table quizzes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  quiz_set_id bigint references public.quiz_sets not null,
  question text check (char_length(question) > 0),
  answer text check (char_length(answer) > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table quizzes enable row level security;
create policy "Individuals can create quizzes." on quizzes for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own quizzes. " on quizzes for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own quizzes." on quizzes for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own quizzes." on quizzes for
    delete using (auth.uid() = user_id);
