name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install packages
      run: yarn install
    - name: Check format
      run: yarn formatter
    - name: Check lint
      run: yarn next lint

